### ISSUE TITLE
Show number of friends online over extension icon

### ISSUE THREAD

**Issue by Bergster** [mnao305/VRCFriendCheck#148]
Firstly, thank you for making this extension. It's very convenient since the only way to check online friends is through the website. Surprised more people don't use this. 

Anyways, it would be even better if we could see the number of online friends hovering over the extension icon. It would be slightly more convenient than having to click the icon to see how many people are online. It would look something like this: https://i.imgur.com/2Jz4ute.png

Thanks again for the great extension!

**Comment by mnao305** [comment]
Hello! Thanks for the great new feature request!
I will start working on the development of this feature :smile:

**Comment by mnao305** [comment]
@Bergster 
Hello!
Just it has released a version 1.4.0 to address this Issue! Please update and check the extension.

This issue will be closed, but if you have any problems or requests for other features, please report the issue again!

I'm using Google Translate

**Comment by Bergster** [comment]
Thanks for adding my suggested feature! I'm only having one issue with it at the moment though. It seems when "Notify only my favorite friends" is enabled, the badge over the extension icon will only show how many of your favorite friends are online, rather than all of your friends. Do you think you could separate this behavior? You could also add an extension option to show either the number of favorite friends online _or_ all your online friends on the badge.

Another interesting behavior to note, if I click the icon and show all my friends, it updates to show the amount of friends you have online (regardless if they are favorited or not). Unfortunately, this will only last for about 5 minutes, then it reverts to only showing number of favorite friends online.

Thanks again, your quickness has been impressive! がんばって！

**Comment by mnao305** [comment]
@Bergster 
Hello!
Added options in Version 1.5.0!
It is now possible to switch the badge display ON and OFF and to switch the number of people displayed on the badge to only favorite friends.

Please update the extension and check it out😆
