### ISSUE TITLE
Notification of favorite friends happens every 5 minutes

### ISSUE THREAD

**Issue by Bergster** [mnao305/VRCFriendCheck#157]
Hello! Since the latest update, if I have the "Notify only my favorite friends" option enabled, I get a notification every 5 minutes telling me which of my favorite friends are online. This seems like unintended behavior; it should rather only notify you once when a favorited friend initially comes online. I assume this happens every 5 minutes because that is the interval when the extension checks the API/servers for who is online.

In the future, you could have a feature that's similar to this bug, where it notifies you every so often who of your favorited friends are online (Example: every 30 minutes you get notified which of your favorited friends are online).

Thank you again for your cooperation and hard work!

**Comment by mnao305** [comment]
Hi!
Thanks for the bug report.

This is an unintended behavior. I will fix it ASAP.

**Comment by mnao305** [comment]
@Bergster 
Hi!
We have fixed this bug in version 1.5.1. Please check it out!

Once again, thank you for reporting this bug.

**Comment by Bergster** [comment]
Hello! I've updated to the latest version, and it seems like the bug is gone now. However, now I'm not getting any notifications when my friends come online! :(

One bug is fixed, and another one takes its place.

Thanks again and good luck!

**Comment by mnao305** [comment]
Hello.
Thank you for reporting the bug again. We will investigate.

**Comment by mnao305** [comment]
@Bergster 
Hello!

We fixed this bug in Version 1.5.2. Sorry it took so long.
If the bug is still there, please report it again.

Thank you again for reporting the bug.

**Comment by mnao305** [comment]
This Issue is closed.
If you have any more problems, please feel free to let me know via Issue.
